### PR TITLE
Removes unneeded argument in ApiUsers.UpdateUserKycDocument; see #52

### PR DESCRIPTION
**Pull request by alexei**
I think this should be released in a separate version, that is have two active versions, one with the deprecation warning, and one with the argument completely removed

### CODE REVIEW

**Comment by alexei** [comment]
As I expected, this branch has conflicts. Will fix them in a minute

**Comment by hobailey** [comment]
OK, no worries - no massive rush anyway as will be a couple of months till this actually gets merged in (and hence they'll probably be more conflicts by then anyway!).

**Comment by alexei** [comment]
I merged master into it and removed the warnings

**Comment by hobailey** [comment]
Closing since there won't be a new minor version of v2, but thanks anyway for the contribution.

**Pull request closed without merging**
