### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Few simple fixes to support Python3 and add a tox.ini to easily test python2.7/3.3/3.4

### CODE REVIEW

**Comment by ilrico** [comment]
I guess the guy answering to you works on a 640K RAM computer... 
"640K ought to be enough for anybody"

**Comment by llann** [comment]
I really do not understand why you don't want your SDK to be comatible with Python 3 AND Python 2 (as the pull request is designed for)?

**Comment by ilrico** [comment]
@Ilann : try Stripe.com for instance, their API is great, and believe me or not, compatible Python 3 (yes, really !)

**Comment by hobailey** [comment]
Hi everyone, sorry for the lack of news. We're just getting this signed off by our developers and we'll update the SDK as soon as we can.

**Comment by llann** [comment]
@ilrico : I didn't knew this payment platform, thanks, looks great :)
@hobailey : Good to know that you are listening and reacting to people's comments :)

**Comment by hobailey** [comment]
Hello again everyone. As you can see from this commit https://github.com/Mangopay/mangopay2-python-sdk/commit/210c313ddee3e0959f26dd8f6721ff6f136c85d0 the SDK is now Python 2.7 and 3 compatible :-)
Thanks for your help and feedback along the way.

**Pull request closed without merging**
