### PR TITLE
Mpsdk 34 add timeout

### PR DESCRIPTION
**Pull request by stefanGhivi**

### CODE REVIEW

**Comment by Changaco** [comment]
Thanks @stefanGhivi. :-)

A lower default timeout may be better, because I think 30 seconds is a common number for web workers (it's the default one of gunicorn at least), and the default timeout for the requests made by the web workers themselves should be lower than their own.

**Comment by gabriellupu** [comment]
@hobailey should we stay with 30s or should we aim for a lower value? @Changaco what timeout value are you thinking about? Thanks.

**Comment by Changaco** [comment]
20 seconds?

**Comment by Changaco** [comment]
Ping.

**Comment by gabriellupu** [comment]
@hobailey 20 seconds is ok?

**Comment by hobailey** [comment]
@gabriellupu I'd prefer to stay with 30s for now, to match the other SDKs please. As long as it's easily configurable, people can update to it as they wish :-)

**Comment by gabriellupu** [comment]
conflicts were solved

**Comment by mickaelpois** [comment]
Thanks @gabriellupu !

**Comment by gabriellupu** [comment]
you're welcome!

**Pull request merged**
